/*-------------------------------------------------------
   Made for the ccs mbed LPC-1768
   By Jordan Heinrichs on for the Solar Car Team
   Copyright (c) 2014 by University of Calgary Solar Car Team
-------------------------------------------------------*/

#include <VehicleData.h>

VehicleData::VehicleData()
: reportedMotorCurrent(0.0f)
, driverSetCurrent(0.0f)
, driverSetCurrentPercentage(0.0f)
, driverSetSpeedRpm(0.0f)
, deadmanPressed(false)
, carDirection(VehicleData::Forward)
, busCurrent(0.0f)
, busVoltage(0.0f)
, vehicleVelocity(0.0f)
, motorVelocityRpm(0.0f)
, phaseCCurrent(0.0f)
, phaseBCurrent(0.0f)
, motorVoltageReal(0.0f)
, motorVoltageImaginary(0.0f)
, motorCurrentReal(0.0f)
, motorCurrentImaginary(0.0f)
, backEmfImaginary(0.0f)
, ipmHeatSinkTemp(0.0f)
, motorTemp(0.0f)
, dspBoardTemp(0.0f)
, dcBusAmpHours(0.0f)
, odometer(0.0f)
, receivedErrorCount(0)
, transmittedErrorCount(0)
, activeMotor(0)
, errorFlags(0)
, limitFlags(0)
, packStateOfCharge(0.0f)
, packStateOfChargePercentage(0.0f)
, balancePackStateOfCharge(0)
, balancePackStateOfChargePercentage(0)
, prechargeDriverStatusFlags(0)
, prechargeState(0)
, contactorSupplyVoltage(0)
, prechargeTimerElapsedFlag(0)
, prechargeTimerCounter(0)
, batteryVoltage(0)
, batteryCurrent(0)
, batteryVoltageThresholdRising(0)
, batteryVoltageThresholdFalling(0)
, bmuStatusFlagsExtended(0)
, fanSpeed0(0)
, fanSpeed1(0)
, fanCurrentConsumption(0)
, cmuCurrentConsumption(0)
, dynamicModeActivated(false)
, secondaryBatteryUnderVoltage(false)
, leftBlinkerActivated(false)
, rightBlinkerActivated(false)
, brakelightOn(false)
, hazardsActivated(false)
, pc(USBTX, USBRX)
{
}
